[package]
name = "miz-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
quick-xml = "0.23.0"
once_cell = "1.12"
enum-map = "2.4"
backtrace = "0.3"
